DELETE FROM actionarchive * CASCADE;
DELETE FROM userstatus * CASCADE;
DELETE FROM useractions * CASCADE;
DELETE FROM posts * CASCADE;
DELETE FROM postarchive * CASCADE;
DELETE FROM boards * CASCADE;
DELETE FROM auth_user * CASCADE;

ALTER SEQUENCE auth_user_id_seq RESTART WITH 1;
ALTER SEQUENCE posts_id_seq RESTART WITH 1;
ALTER SEQUENCE boards_id_seq RESTART WITH 1;
ALTER SEQUENCE useractions_id_seq RESTART WITH 1;